title: zew0z
description: My journey into the space of cyber security and tech. CTF writeups, notes, and flags.
url: https://zew0z.github.io
lang: en
author: zew0z

permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      image: /favicon.ico
